"""add FrameDebugInfo

Revision ID: 0ad1be484c75
Revises: 20ec14552103
Create Date: 2018-06-06 14:40:29.151086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ad1be484c75'
down_revision = '20ec14552103'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('frame_debug_info',
    sa.Column('text_event', sa.String(length=255), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('frame_num', sa.Integer(), nullable=False),
    sa.Column('changed_pixels', sa.Integer(), nullable=True),
    sa.Column('threshold', sa.Integer(), nullable=True),
    sa.Column('noise', sa.Integer(), nullable=True),
    sa.Column('despeckle_labels', sa.Integer(), nullable=True),
    sa.Column('image_width', sa.Integer(), nullable=True),
    sa.Column('image_height', sa.Integer(), nullable=True),
    sa.Column('motion_width', sa.Integer(), nullable=True),
    sa.Column('motion_height', sa.Integer(), nullable=True),
    sa.Column('motion_center_x', sa.Integer(), nullable=True),
    sa.Column('motion_center_y', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['text_event'], ['motion_events.text_event'], name=op.f('fk_frame_debug_info_text_event_motion_events')),
    sa.PrimaryKeyConstraint('text_event', 'date', 'frame_num', name=op.f('pk_frame_debug_info')),
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('frame_debug_info')
    # ### end Alembic commands ###
