"""add Notification model

Revision ID: 20ec14552103
Revises: c6d3263fdc01
Create Date: 2018-05-26 14:11:34.801729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20ec14552103'
down_revision = 'c6d3263fdc01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_name', sa.String(length=255), nullable=True),
    sa.Column('video_filename', sa.String(length=255), nullable=True),
    sa.Column('text_event', sa.String(length=255), nullable=True),
    sa.Column('generated_time', sa.DateTime(), nullable=True),
    sa.Column('sent_time', sa.DateTime(), nullable=True),
    sa.Column('num_retries', sa.Integer(), nullable=True),
    sa.Column('provider_response', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['text_event'], ['motion_events.text_event'], name=op.f('fk_notifications_text_event_motion_events')),
    sa.ForeignKeyConstraint(['video_filename'], ['videos.filename'], name=op.f('fk_notifications_video_filename_videos')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications')),
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications')
    # ### end Alembic commands ###
