"""add db-stored settings table

Revision ID: f4fff0d0ab67
Revises: 9c6832baac37
Create Date: 2018-05-26 06:57:50.015081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4fff0d0ab67'
down_revision = '9c6832baac37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
